# Generated by Django 5.0.6 on 2024-08-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expanded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='sort_order',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
