# Generated by Django 5.0.6 on 2024-08-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_stock_productgallery_variation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='variation',
        ),
    ]
