# Generated by Django 5.0.6 on 2024-08-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_productgallery_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='stock',
        ),
    ]
