# Generated by Django 5.0.6 on 2024-08-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productgallery_variation_variation_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.variation'),
        ),
    ]
