# Generated by Django 5.0.6 on 2024-08-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_price',
            field=models.FloatField(),
        ),
    ]
