# Generated by Django 5.0.6 on 2024-08-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_productgallery_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='sort_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
