# Generated by Django 4.1.2 on 2024-09-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_productgallery_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='store/products/videos/'),
        ),
    ]
