# Generated by Django 4.1.2 on 2024-09-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_productgallery_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='store/products/'),
        ),
    ]
