# Generated by Django 4.1.2 on 2024-10-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_productgallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='video',
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(default=0, max_length=255, upload_to='store/products/'),
            preserve_default=False,
        ),
    ]
