# Generated by Django 4.1.2 on 2025-01-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_productgallery_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article_nummer',
            field=models.CharField(default='0000', max_length=25),
        ),
    ]
