# Generated by Django 5.0.6 on 2024-08-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='house_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
