# Generated by Django 5.0.6 on 2024-08-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_order_total_alter_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
