# Generated by Django 5.0.6 on 2024-08-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_order_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ip',
        ),
    ]
